### ISSUE TITLE
`stat_bin` error message hard to overcome

### ISSUE THREAD

**Issue by eddelbuettel** [ggobi/ggally#184]
`ggpairs` is lovely.  But consider this

```r
R> set.seed(42)
R> df <- data.frame(G=sample(c('M','F'), 20, replace=TRUE), W=170+rnorm(20)*sqrt(25))
R> ggpairs(df)
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
R> 
```

Doing [the usual](https://devhumor.com/media/googling-the-error-message) only reveals loads of similar error message _in your own vignettes_.   Mucking with `mapping=...` lead nowhere.   

Can you spare a moment for a struggling artist and show how this message can be avoided, and / or how  `binwidth` can be set?

**Comment by eddelbuettel** [comment]
Ok, proudly talking to myself here.  With

```r
my_bin <- function(data, mapping, ..., low = "#132B43", high = "#56B1F7") {
  ggplot(data = data, mapping = mapping) +
    geom_bin2d(...) +
    scale_fill_gradient(low = low, high = high)
}
```

borrowed from the vignette we can do

```r
ggpairs(df, lower=list(combo=wrap("facethist", binwidth=1), 
                                       continuous=wrap(my_bin, binwidth=0.25)))
```

which is finally free of errors and hence suitable for Rmd output.    A little involved though.  Easier ways, anyone?

**Comment by eddelbuettel** [comment]
Ah. At last:

```r
ggpairs(df, lower=list(combo=wrap("facethist", binwidth=0.8)))
```

Much simpler.  Could this be added to the `ggpairs` examples section, please?

**Comment by schloerke** [comment]
Sounds good to me!

Thank you for your workflow! Helps me out as well

- Barret

**Comment by eddelbuettel** [comment]
Hm, in that case should it be a top-level argument to `ggpairs` to be dispatched down this way if set?

**Comment by schloerke** [comment]
It use to be. But now I strongly believe it's the wrong approach.

binwidth doesn't make sense when it's applied to a "non histogram" plot. If
it's a top level arg then it'll be difficult to determine where it should
be applied.

There is also issues name clashing. Such as geom_smooth has a method arg
that takes "lm" and "loess" while ggally_cor has "method" that's passed
directly to cor with a default value of "pearson" (which doesn't match
geom_smooth).

Since ggpairs now accepts custom functions, I think it's best to provide an
altered function that can handle any level of arg customization.

**Comment by eddelbuettel** [comment]
I trust your judgement in the matter.  But an example showing how to set it, given that the help text displayed both directly and after invoking `mapping=` is not exactly, err. comprehensible, would go a long way.

**Comment by schloerke** [comment]
Sounds good to me! It'll make sure it's in the next release. :-)
