### ISSUE TITLE
One necessary library does not loading

### ISSUE THREAD

**Issue by mmaku** [ggobi/ggally#220]
Library _broom_ necessary to use _ggnostic_ function does not loading at library loading and has to be loaded manually. 
Not a big deal, but it could be added for faster/easier usage.

**Comment by schloerke** [comment]
can you give me a reproducible example? I can't repeat it on my end.

Thank you!

**Comment by mmaku** [comment]
HI, right now I cant, It seems like during istalation of 'GGally' 
'broom' wasn't installed. Right now when I installed 'broom' error 
doesn't occur.

but i tried to reproduce it:

///rm(list = ls()) //
//
//library(PBImisc)//
//library(ggplot2)//
//remove.packages("broom")//
//remove.packages("GGally")//
//install.packages("GGally")//
//library(GGally)//
//# install.packages("broom")//
//# library(broom)//
//
//data("apartments")//
//attach(apartments)//
//
//ggnostic(lm(m2.price~surface))//
/

I receive following error:

Error in require_pkgs("broom") : please install the package 'broom'. 
install.packages('broom')

Regards, Michal


W dniu 29.11.2016 o 23:06, Barret Schloerke pisze:

**Comment by schloerke** [comment]
Hi Michal,

I would say this is expected behavior.  `broom` is a suggested package, as it is not necessary for all the different sections to operate. Mainly just ggnostic and ggcoef.  (Similar situation with `igraph` for the network functions in GGally.).

I'm going to close this as the error message is informative. 

The error could be also be avoided if all dependencies are installed with GGally. 

```r
install.packages("GGally", dependencies = TRUE)
library(GGally)
ggnostic(lm(mpg ~ am + wt, data = mtcars))
```

Thank you for the reproducible example! It helps a lot.

Best,
Barret
