### ISSUE TITLE
Difference between if statement and error message in ggsurv_m

### ISSUE THREAD

**Issue by v624** [ggobi/ggally#222]
When using confidence intervals in a plot with multiple strata in ggsurv(), the error message _"Either surv.col or lty.est should be of length 1 in order to plot 95% CI with multiple strata"_ can be encountered. However, the if statement and the error message does not agree:

```R
if (length(surv.col) > 1 || length(lty.est) > 1) {
   stop("Either surv.col or lty.est should be of length 1 in order to plot 95% CI with multiple strata")
```
I think that the error message is correct, while the if statement is not. My guess is that the code should be changed to:
```R
if (length(surv.col) != 1 & length(lty.est) != 1) {
   stop("Either surv.col or lty.est should be of length 1 in order to plot 95% CI with multiple strata")
```

**Comment by schloerke** [comment]
@EdwinTh 

Do you think this error message is needed anymore? https://github.com/ggobi/ggally/blob/6f96dcf2afc1aa8b50b58608452c5406dad006df/R/ggsurv.R#L295

I think `surv.col` length check is covered here: https://github.com/ggobi/ggally/blob/6f96dcf2afc1aa8b50b58608452c5406dad006df/R/ggsurv.R#L274
and `lty.est` length check is covered here: https://github.com/ggobi/ggally/blob/6f96dcf2afc1aa8b50b58608452c5406dad006df/R/ggsurv.R#L286

If so, we might as well remove the stop check.

**Comment by EdwinTh** [comment]
I cannot figure out why I introduced the stop check in the first place. Although specifying both multiple surv.col and multiple lty.est gives a bit of a circus, technically there is nothing wrong with it. 

The checks you mention, Barret, do not check for the combination of the two parameters, so in that sense the check is not redundant. However I still opt for removing it, because it is for the user to decide if both should be specified.

**Comment by schloerke** [comment]
removed error check. submitting to cran
