### ISSUE TITLE
Variable attributes and `plotting_data_type`

### ISSUE THREAD

**Issue by ewenharrison** [ggobi/ggally#288]
Sorry to bother again. 

I support `Hmisc::label()` in the `finalfit` package. A labelled continuous variable is treated as discrete in `ggpairs` and `ggduo`. . 

```
data(flea)
ggpairs(flea, columns = 2:4)
Hmisc::label(flea$head) = "Head"
ggpairs(flea, columns = 2:4)
```

Would this work?

``` diff
plotting_data_type <- function(x) {
	if (all(is.na(x))) {
		return("na")
	}
	if (is_date(x)) {
		"continuous"
-	} else if (!is.null(attributes(x)) || all(is.character(x)) || is.logical(x)) {
+	} else if (is.factor(x)) || all(is.character(x)) || is.logical(x)) {
		"discrete"
	} else {
		"continuous"
	}
}
```

**Comment by schloerke** [comment]
These issues are very welcome!  Thank you.

It's very old code.  I believe this was the original intent and your version would be much clearer.

There's an extra close paren on `is.factor`, but looks great otherwise.  Want to submit a PR?  Could you also remove the `all()` around `is.character` and upgrade the if statement to use `any()` instead of `||`?
