### ISSUE TITLE
Consider adding frequency label as an option in ggbivariate?

### ISSUE THREAD

**Issue by billster45** [ggobi/ggally#376]
Hi, I really like ggbivariate. As an option, could the function allow users to display the frequency instead of the percentage? This is useful where there are low numbers in categories and the percentage could be misleading. Example below of using ggbivariate then the same plot but with frequency labels instead of percentage.

library(tidyverse)
library(GGally)

# GGally ggbivariate
mtcars %>% 
  dplyr::mutate_all(as.factor) %>% 
  GGally::ggbivariate(outcome = "vs", explanatory = "gear")

# GGally with bivariate with frequency label option?
mtcars %>% 
  dplyr::group_by(gear,vs) %>% 
  dplyr::summarise(n = dplyr::n()) %>% 
  dplyr::mutate(vs = as.factor(vs)) %>% 
  ggplot2::ggplot() +
  ggplot2::aes(x = gear,
               y = n,
               fill = vs,
               label = n) +
  ggplot2::geom_bar(position="fill", 
                    stat="identity") +
  ggplot2::geom_text(size = 3, 
                     position = position_fill(vjust = 0.5),
                     colour = "black") +
  ggplot2::coord_flip() +
  ggplot2::scale_y_continuous(labels = scales::percent)

**Comment by larmarange** [comment]
Could be done. Just require an additional argument for `ggally_colbar()` and `ggally_rowbar()`.

I will have a look at it this week.

**Comment by larmarange** [comment]
So, with this commit 31847534323a9a81be21208a38ecd0022f62e3dd you can now pass a label aesthetic to `ggally_rowbar()`

```r
ggbivariate(tips, "smoker", c("day", "time", "sex"), mapping = aes(label = after_stat(count)))
```

will produce

![image](https://user-images.githubusercontent.com/966307/84779985-57955f00-afe5-11ea-9be7-ca0ceeb20380.png)

However, there is an issue if a continuous variable is provided.

```r
ggbivariate(tips, "smoker", c("day", "time", "sex", "tip"), mapping = aes(label = after_stat(count)))
```

an error occurs because `after_stat(count)` is not available for box plots.

```
Erreur : Aesthetics must be valid computed stats. Problematic aesthetic(s): label = after_stat(count). 
Did you map your stat in the wrong layer?
Run `rlang::last_error()` to see where the error occurred.
De plus : Warning message:
 Erreur : Aesthetics must be valid computed stats. Problematic aesthetic(s): label = after_stat(count). 
Did you map your stat in the wrong layer?
Run `rlang::last_error()` to see where the error occurred. 
```

Dear @schloerke I need your advice. Here an option would be to pass an aesthetic only to `ggally_rowbar()`.

However, it seems not possible when using `wrap()`.

```r
ggduo(tips, columnsX = "smoker", columnsY = "day", types = list(discrete = wrap(ggally_colbar, mapping = aes(label = after_stat(count)))))
ggbivariate(tips, "smoker", c("day", "time", "sex", "tip"), rowbar_args = list(mapping = aes(label = after_stat(count))))
```

in these two examples, the mapping is not passed through. Should we consider an evolution of `wrap()`?

Another possibility, would be to replace the `label_format` argument in `ggally_colbar()` and `ggally_rowbar()` by a `label` argument passed to `aes_string()`.

The default value would be `label = "scales::percent(after_stat(prop), accuracy = .1)"`  allowing to provide `label = "after_stat(count)"` as a parameter.

However, it would change the signature of `ggally_rowbar()` and `ggally_colbar()`, but it is maybe not a problem as these functiosn are quite new.

**Comment by billster45** [comment]
Awesome! Thanks @larmarange I'll try it today.
