### ISSUE TITLE
reshape vs. reshape2

### ISSUE THREAD

**Issue by schloerke** [ggobi/ggally#92]
@briatte makes a good point.  

I know reshape2 is faster.  My main motivation was to use the tips dataset and to use melt.  I honestly haven't made a big/any effort into reshape2.

@briatte, can you take a look for issues or make a pull request that upgrades reshape to reshape2?

Thank you,
Barret

**Comment by briatte** [comment]
It shouldn't be too hard to remove reshape entirely: [there aren't that many calls to it](https://github.com/ggobi/ggally/search?utf8=%E2%9C%93&q=importfrom+reshape&type=Code) in the code. As for `tips`, shouldn't it be possible to use the `happy` dataset instead? Both are surveys, IIRC.

**Comment by briatte** [comment]
@schloerke I've explored the matter, and switching to `reshape2` is doable. I've managed to build a `R CMD CHECK`-valid version of `GGally` without using `reshape` at all, using just `reshape2` instead.

This, however, requires copying a few functions from `reshape` directly into `GGally`. [Here's a Gist](https://gist.github.com/briatte/1186e865c311c6104531) that shows all required imports:

- add.all.combinations
  - expand.grid.df
  - sort_df
- rescaler.default
  - rescaler.data.frame

The last two were already in `GGally` due to importing difficulties.

What do you think? Now that I've explored the matter, I think it's better to stick with importing `reshape` (which is only 125 KB), so as to clearly show that `GGally` depends on the functions above by Hadley Wickham.

**Comment by schloerke** [comment]
keeping reshape sounds good to me.  Yup, it gives credit and we can't easily drop those functions.

Thank you!
